version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: example-database
    environment:
      POSTGRES_DB: example-database
      POSTGRES_USER: example-database
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
    networks:
      - pg-network
    volumes:
      - pg-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pg-admin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: mysecretpassword
    ports:
      - "5050:80"
    networks:
      - pg-network

  app: 
    image: urlshortner
    container_name: urlshortner
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - POSTGRES_DB=example-database
      - POSTGRES_USER=example-database
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_HOST=postgres
      - POSTGRES_DIALECT=postgres
    depends_on:
      - postgres
    networks:
      - pg-network

networks:
  pg-network:

volumes:
  pg-data: